#! /bin/sh

/bin/mount -a

mkdir -p /root
mkdir -p /home
mkdir -p /proc
mkdir -p /sys
mkdir -p /var/empty
mkdir -p /var/run
mkdir -p /var/log
mkdir -p /dev/pts
touch /var/log/wtmpx

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts

mdev -s

ifconfig eth0 up
ifconfig eth0 192.168.1.200 netmask 255.255.255.0
ifconfig lo up

ssh-keygen -t rsa1 -f /usr/local/etc/ssh_host_key -N ""
ssh-keygen -t rsa -f /usr/local/etc/ssh_host_rsa_key -N ""
ssh-keygen -t dsa -f /usr/local/etc/ssh_host_dsa_key -N ""
ssh-keygen -t ecdsa -f /usr/local/etc/ssh_host_ecdsa_key -N ""
ssh-keygen -t ed25519 -f /usr/local/etc/ssh_host_ed25519_key -N ""

inetd /etc/inetd.conf
klogd
syslogd
/sbin/sshd

hostname mithrandir

export TERM=linux3.0
